# Generated by Django 2.0.2 on 2018-02-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('code', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('is_open', models.BooleanField()),
                ('french_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('russian_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'Structure_2 атрибуты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'LMRussia отдел',
                'verbose_name_plural': 'LMRussia_1 отделы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAdeo',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'отдел Adeo',
                'verbose_name_plural': 'Adeo_1 отделы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.Attribute')),
            ],
            options={
                'verbose_name': 'связь',
                'verbose_name_plural': 'связи',
                'ordering': ['value', 'attribute', 'model'],
            },
        ),
        migrations.CreateModel(
            name='LMCode',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('avs', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.Department')),
            ],
            options={
                'verbose_name': 'lm код',
                'verbose_name_plural': 'Structure_4 lm коды',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('french_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('russian_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'модель Адео',
                'verbose_name_plural': 'Structure_1 модели Адео',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModelGroupAdeo',
            fields=[
                ('code', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Adeo группа моделей',
                'verbose_name_plural': 'Adeo_3 группы моделей',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubDepartmentAdeo',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('department_adeo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.DepartmentAdeo')),
            ],
            options={
                'verbose_name': 'подотдел Adeo',
                'verbose_name_plural': 'Adeo_2 подотделы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('french_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('russian_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'значение атрибута',
                'verbose_name_plural': 'Structure_3 значения атрибутов',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='modelgroupadeo',
            name='sub_department_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.SubDepartmentAdeo'),
        ),
        migrations.AddField(
            model_name='model',
            name='model_group_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.ModelGroupAdeo'),
        ),
        migrations.AddField(
            model_name='lmcode',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.Model'),
        ),
        migrations.AddField(
            model_name='link',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.Model'),
        ),
        migrations.AddField(
            model_name='link',
            name='value',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='models_table.Value'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('model', 'attribute', 'value')},
        ),
    ]
