# Generated by Django 2.0.2 on 2018-02-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMCodeAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.Attribute')),
                ('lm_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models_table.LMCode')),
            ],
        ),
    ]
