# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0002_lmcodeattributevalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdepartmentadeo',
            options={'ordering': ['id'], 'verbose_name': 'подотдел Adeo', 'verbose_name_plural': 'Adeo_2 подотделы'},
        ),
        migrations.RenameField(
            model_name='subdepartmentadeo',
            old_name='code',
            new_name='id',
        ),
    ]
