# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0003_auto_20180207_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['id'], 'verbose_name': 'атрибут', 'verbose_name_plural': 'Structure_2 атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': 'LMRussia отдел', 'verbose_name_plural': 'LMRussia_1 отделы'},
        ),
        migrations.AlterModelOptions(
            name='departmentadeo',
            options={'ordering': ['id'], 'verbose_name': 'отдел Adeo', 'verbose_name_plural': 'Adeo_1 отделы'},
        ),
        migrations.AlterModelOptions(
            name='lmcode',
            options={'ordering': ['id'], 'verbose_name': 'lm код', 'verbose_name_plural': 'Structure_4 lm коды'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['id'], 'verbose_name': 'модель Адео', 'verbose_name_plural': 'Structure_1 модели Адео'},
        ),
        migrations.AlterModelOptions(
            name='modelgroupadeo',
            options={'ordering': ['id'], 'verbose_name': 'Adeo группа моделей', 'verbose_name_plural': 'Adeo_3 группы моделей'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['id'], 'verbose_name': 'значение атрибута', 'verbose_name_plural': 'Structure_3 значения атрибутов'},
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='departmentadeo',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='lmcode',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='modelgroupadeo',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='code',
            new_name='id',
        ),
    ]
