# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0004_auto_20180207_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmcode',
            name='avs',
            field=models.DateField(blank=True),
        ),
    ]
