# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0005_auto_20180207_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmcode',
            name='id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
