# Generated by Django 2.0.2 on 2018-02-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0008_auto_20180207_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmcodeattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='lmcodeattributevalue',
            name='lm_code',
        ),
        migrations.DeleteModel(
            name='LMCodeAttributeValue',
        ),
    ]
