# Generated by Django 2.0.2 on 2018-02-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0009_auto_20180207_0855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
    ]
