# Generated by Django 2.0.2 on 2018-02-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0010_auto_20180207_1127'),
        ('models_table', '0011_auto_20180207_1404'),
    ]

    operations = [
    ]
