# Generated by Django 2.0.2 on 2018-02-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0012_merge_20180207_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='english_name',
            field=models.CharField(max_length=200, verbose_name='Наименование ENG'),
        ),
        migrations.AlterField(
            model_name='model',
            name='french_name',
            field=models.CharField(max_length=200, verbose_name='Наименование FRA'),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Номер модели'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_group_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.ModelGroupAdeo'),
        ),
        migrations.AlterField(
            model_name='model',
            name='russian_name',
            field=models.CharField(max_length=200, verbose_name='Наименование RUS'),
        ),
        migrations.AlterField(
            model_name='modelgroupadeo',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modelgroupadeo',
            name='sub_department_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.SubDepartmentAdeo', verbose_name='Подкатегория Адео'),
        ),
    ]
