# Generated by Django 2.0.2 on 2018-02-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0013_auto_20180207_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.Attribute'),
        ),
        migrations.AlterField(
            model_name='link',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.Model'),
        ),
        migrations.AlterField(
            model_name='link',
            name='value',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='models_table.Value'),
        ),
        migrations.AlterField(
            model_name='lmcode',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.Department'),
        ),
        migrations.AlterField(
            model_name='lmcode',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.Model'),
        ),
        migrations.AlterField(
            model_name='subdepartmentadeo',
            name='department_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.DepartmentAdeo'),
        ),
    ]
