# Generated by Django 2.0.2 on 2018-02-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0014_auto_20180207_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='french_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='russian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lmcode',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='french_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='russian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelgroupadeo',
            name='sub_department_adeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.SubDepartmentAdeo'),
        ),
        migrations.AlterField(
            model_name='value',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='french_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='russian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
