# Generated by Django 2.0.2 on 2018-02-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0015_auto_20180207_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.Attribute')),
                ('lmcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_table.LMCode')),
            ],
            options={
                'verbose_name': 'Значение для кода',
                'verbose_name_plural': 'Значения для кодов',
                'ordering': ['lmcode'],
            },
        ),
    ]
