# Generated by Django 2.0.2 on 2018-02-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_table', '0016_codevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_table.Value'),
        ),
    ]
